# Generated by Django 4.0.6 on 2022-07-09 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_network_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='network',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='alumni_network_app.network'),
        ),
    ]
