# Generated by Django 4.0.6 on 2022-07-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_network_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
