# Generated by Django 4.0.5 on 2022-07-01 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_network_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='network',
        ),
        migrations.RemoveField(
            model_name='post',
            name='conversation',
        ),
        migrations.AddField(
            model_name='post',
            name='network',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='alumni_network_app.network'),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(default='Life', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='alumni_network_app.network'),
        ),
        migrations.AlterField(
            model_name='user',
            name='socialmedia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='alumni_network_app.socialmedia'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='alumni_network_app.post'),
        ),
    ]
