# Generated by Django 4.0.6 on 2022-07-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_network_app', '0002_alter_network_logo_alter_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='network',
            new_name='networks',
        ),
    ]
