# Generated by Django 4.0.6 on 2022-07-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_network_app', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='error@nope.com', max_length=254),
        ),
    ]
