# Generated by Django 4.0.6 on 2022-07-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_network_app', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageURL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
