# Generated by Django 4.0.6 on 2022-08-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_network_app', '0012_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateTime',
            field=models.CharField(max_length=100),
        ),
    ]
